# Generated by Django 4.1 on 2022-08-24 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('transaction', models.CharField(choices=[('rental', 'rental'), ('sale', 'sale')], default='sale', max_length=32)),
                ('type', models.CharField(choices=[('apartment', 'apartment'), ('house', 'house')], default='apartment', max_length=32)),
                ('address', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garage', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('description', models.CharField(default='', max_length=1000)),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_1', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_2', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_3', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_4', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_5', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('photo_6', models.ImageField(upload_to='photo/%Y/%m/%d')),
                ('agent', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='estatesite.agent')),
            ],
        ),
    ]
