# Generated by Django 4.1 on 2022-09-05 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estatesite', '0004_alter_property_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='estatesite.agent'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction',
            field=models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale')], default='sale', max_length=32),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House')], default='apartment', max_length=32),
        ),
    ]
